export const MENTORS = [
  {
    id: 1,
    name: "Arjun Sharma",
    role: "Software Engineer",
    company: "Google",
    college: "IIT Bombay",
    batch: "2019",
    field: "Engineering",
    specialization: "Computer Science",
    rating: 4.9,
    sessions: 142,
    image: "AS",
    color: "from-blue-400 to-blue-600",
    tags: ["Coding", "Placements", "DSA"],
    bio: "IIT-B CS grad now at Google. Cracked JEE Advanced AIR 89 after learning from Vedantu.",
    available: true,
  },
  {
    id: 2,
    name: "Priya Mehta",
    role: "Resident Doctor",
    company: "AIIMS Delhi",
    college: "AIIMS Delhi",
    batch: "2020",
    field: "Medicine",
    specialization: "MBBS",
    rating: 4.8,
    sessions: 98,
    image: "PM",
    color: "from-pink-400 to-rose-500",
    tags: ["NEET", "Biology", "Study Plan"],
    bio: "NEET AIR 312. Now a doctor at AIIMS. Passionate about helping future doctors find their path.",
    available: true,
  },
  {
    id: 3,
    name: "Rohit Verma",
    role: "Investment Banker",
    company: "Goldman Sachs",
    college: "IIM Ahmedabad",
    batch: "2021",
    field: "Finance",
    specialization: "MBA Finance",
    rating: 4.7,
    sessions: 76,
    image: "RV",
    color: "from-emerald-400 to-teal-600",
    tags: ["Finance", "CAT Prep", "Careers"],
    bio: "Commerce stream to IIM-A. Aced CAT with 99.8 percentile. Now cracking deals at GS.",
    available: false,
  },
  {
    id: 4,
    name: "Ananya Singh",
    role: "Civil Services Officer",
    company: "IAS — Maharashtra Cadre",
    college: "St. Stephen's College",
    batch: "2018",
    field: "Civil Services",
    specialization: "UPSC",
    rating: 5.0,
    sessions: 203,
    image: "AS",
    color: "from-violet-400 to-purple-600",
    tags: ["UPSC", "Essay Writing", "GS"],
    bio: "AIR 34 in UPSC 2022. Started journey as a Vedantu student in Class 10. Now giving back.",
    available: true,
  },
  {
    id: 5,
    name: "Dev Patel",
    role: "Machine Learning Engineer",
    company: "Microsoft Research",
    college: "IIT Delhi",
    batch: "2020",
    field: "Engineering",
    specialization: "AI/ML",
    rating: 4.9,
    sessions: 119,
    image: "DP",
    color: "from-sky-400 to-blue-500",
    tags: ["AI/ML", "Research", "JEE"],
    bio: "JEE Advanced AIR 45. Now building AI at Microsoft. Happy to mentor aspiring engineers.",
    available: true,
  },
  {
    id: 6,
    name: "Kavita Rao",
    role: "Chartered Accountant",
    company: "Deloitte India",
    college: "SRCC Delhi",
    batch: "2019",
    field: "Commerce",
    specialization: "CA Final",
    rating: 4.6,
    sessions: 87,
    image: "KR",
    color: "from-amber-400 to-orange-500",
    tags: ["CA", "Accounts", "Commerce"],
    bio: "First attempt CA qualifier. Helping commerce students navigate their career paths smartly.",
    available: true,
  },
];

export const SUCCESS_STORIES = [
  {
    id: 1,
    name: "Siddharth Kulkarni",
    result: "JEE Advanced AIR 127",
    mentor: "Dev Patel",
    quote:
      "My mentor Dev shared his exact prep strategy and helped me fix my Physics weak spots in just 3 sessions. Game changer.",
    field: "Engineering",
    college: "IIT Kharagpur",
    image: "SK",
    color: "from-blue-400 to-indigo-500",
  },
  {
    id: 2,
    name: "Meera Nair",
    result: "NEET AIR 203",
    mentor: "Priya Mehta",
    quote:
      "Priya didi mapped out my entire NEET calendar and told me exactly what AIIMS expects. I couldn't have done it without her.",
    field: "Medicine",
    college: "Maulana Azad Medical College",
    image: "MN",
    color: "from-pink-400 to-rose-500",
  },
  {
    id: 3,
    name: "Aakash Gupta",
    result: "CAT 99.2 Percentile",
    mentor: "Rohit Verma",
    quote:
      "Rohit bhai broke down the entire CAT strategy in 2 sessions. His real-world finance insights made me confident in GD-PI too.",
    field: "Finance",
    college: "IIM Calcutta",
    image: "AG",
    color: "from-emerald-400 to-green-600",
  },
  {
    id: 4,
    name: "Riya Desai",
    result: "UPSC AIR 89",
    mentor: "Ananya Singh",
    quote:
      "Ananya ma'am's framework for essay writing and interview prep was invaluable. She reviewed my answers personally.",
    field: "Civil Services",
    college: "LBSNAA",
    image: "RD",
    color: "from-violet-400 to-purple-600",
  },
];

export const CAREER_TRACKS = [
  {
    id: "engineering",
    label: "Engineering",
    icon: "⚙️",
    exams: ["JEE Main", "JEE Advanced", "BITSAT"],
    mentors: 124,
    color: "blue",
  },
  {
    id: "medicine",
    label: "Medicine",
    icon: "🩺",
    exams: ["NEET UG", "NEET PG", "AIIMS"],
    mentors: 89,
    color: "rose",
  },
  {
    id: "finance",
    label: "Finance & MBA",
    icon: "📈",
    exams: ["CAT", "XAT", "GMAT"],
    mentors: 67,
    color: "emerald",
  },
  {
    id: "civil",
    label: "Civil Services",
    icon: "🏛️",
    exams: ["UPSC CSE", "State PCS"],
    mentors: 52,
    color: "violet",
  },
  {
    id: "law",
    label: "Law",
    icon: "⚖️",
    exams: ["CLAT", "AILET"],
    mentors: 38,
    color: "amber",
  },
  {
    id: "design",
    label: "Design & Arts",
    icon: "🎨",
    exams: ["NID", "NIFT", "UCEED"],
    mentors: 29,
    color: "pink",
  },
];

export const UPCOMING_SESSIONS = [
  {
    id: 1,
    title: "Cracking JEE Advanced: My AIR 45 Story",
    host: "Dev Patel",
    role: "IIT Delhi | Microsoft",
    date: "April 5, 2026",
    time: "6:00 PM IST",
    duration: "60 min",
    attendees: 312,
    type: "Live Webinar",
    color: "blue",
  },
  {
    id: 2,
    title: "NEET 2026 — Last 60 Days Master Plan",
    host: "Priya Mehta",
    role: "AIIMS Delhi",
    date: "April 7, 2026",
    time: "7:30 PM IST",
    duration: "90 min",
    attendees: 487,
    type: "Workshop",
    color: "rose",
  },
  {
    id: 3,
    title: "From Commerce to IIM: My Unfiltered Journey",
    host: "Rohit Verma",
    role: "IIM-A | Goldman Sachs",
    date: "April 10, 2026",
    time: "5:00 PM IST",
    duration: "75 min",
    attendees: 218,
    type: "AMA Session",
    color: "emerald",
  },
];

export const STATS = [
  { value: "50,000+", label: "Alumni Registered" },
  { value: "2.4L+", label: "Mentorship Sessions" },
  { value: "180+", label: "Career Paths Covered" },
  { value: "94%", label: "Learners Saw Results" },
];
